{
 "title": "k6 부하 테스트 결과",
 "description": "Prometheus 네이티브 히스토그램으로 저장된 k6 OSS 결과를 시각화합니다.",
 "tags": [
  "prometheus",
  "k6",
  "native-histogram"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "프로메테우스 DS", "query": "prometheus" },
   { "name": "testid", "label": "테스트 ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile", "label": "추세 메트릭 쿼리", "query": "0.99" },
   { "name": "adhoc_filter", "label": "임시 필터" }
  ]
 },
 "panels": [
  {
   "title": "성능 개요",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_duration_q$quantile"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  {
   "title": "성능 개요",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 요청",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k6_http_reqs_total{testid=~\"$testid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 요청 실패",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "k6_http_req_failed_rate", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "최대 RPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 요청 시간",
     "type": "stat",
     "description": "Select a different quantile to change the query",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "전송률",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "data_sent"
      },
      {
       "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "data_received"
      }
     ]
    },
    {
     "title": "Iterations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_iteration_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "iteration_duration_q$quantile"
      },
      {
       "expr": "avg(k6_dropped_iterations_total{testid=~\"$testid\"})",
       "legendFormat": "dropped_iterations"
      }
     ]
    },
    {
     "title": "TPS (Iterations per Second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops/sec" } },
     "targets": [
      {
       "expr": "irate(k6_iterations_total{testid=~\"$testid\"}[$__rate_interval])",
       "legendFormat": "TPS"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 지연 시간",
     "type": "timeseries",
     "description": "Select a different quantile to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_blocked_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_blocked_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_tls_handshaking_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_sending_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_sending_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_waiting_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_receiving_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_receiving_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_duration_q$quantile"
      }
     ]
    },
    {
     "title": "HTTP 지연 통계",
     "type": "timeseries",
     "description": "Select a different quantile to change the query",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
       "legendFormat": "http_req_duration_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval])))",
       "legendFormat": "success_http_req_duration_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval])))",
       "legendFormat": "errors_http_req_duration_q$quantile"
      }
     ]
    },
    {
     "title": "HTTP 요청률",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "http_req_s"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_errors"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_success"
      }
     ]
    },
    {
     "title": "URL별 요청",
     "type": "table",
     "description": "min/max/p95/p99 depends on the available Quantile Stats",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "min"
      },
      {
       "expr": "histogram_quantile(1, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Spring Boot 애플리케이션 메트릭", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "DB 연결 (HikariCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"springboot-test\"}",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"springboot-test\"}",
     "legendFormat": "Pending Connections"
    }
   ]
  },
  {
   "title": "JVM 힙 메모리",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", job=\"springboot-test\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", job=\"springboot-test\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"springboot-test\"}",
     "legendFormat": "Process CPU Usage"
    },
    {
     "expr": "system_cpu_usage{job=\"springboot-test\"}",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "GC 성능",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"springboot-test\"}[$__rate_interval])",
     "legendFormat": "GC Pause Sum"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{job=\"springboot-test\"}",
     "legendFormat": "GC Pause Max"
    }
   ]
  },
  {
   "title": "웹 서버 스레드 (Tomcat)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "executor_pool_size_threads{job=\"springboot-test\"}",
     "legendFormat": "Current Threads"
    },
    {
     "expr": "executor_active_threads{job=\"springboot-test\"}",
     "legendFormat": "Busy Threads"
    }
   ]
  },
  {
   "title": "검증",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "검증 목록",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "round(k6_checks_rate{testid=~\"$testid\"}, 0.1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "검증 성공률 (개별 검증 집계)",
     "type": "timeseries",
     "description": "Filter by check name to query a particular check",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg(round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
       "legendFormat": "k6_checks_rate"
      }
     ]
    }
   ]
  }
 ]
}