global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-k6'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'springboot-test'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'springboot-test:8088' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
