global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'springboot:8088' ]

  - job_name: 'springboot-test-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'springboot-test:8088' ]

  - job_name: 'fastapi-app'
    static_configs:
      - targets: [ 'fastapi:8000' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]
